const EVOLUTIONS = {
  "Bulbasaur":{
    "level":"16",
    "to":"Ivysaur"
  },
  "Ivysaur":{
    "level":"32",
    "to":"Venusaur"
  },
  "Charmander":{
    "level":"16",
    "to":"Charmeleon"
  },
  "Charmeleon":{
    "level":"36",
    "to":"Charizard"
  },
  "Squirtle":{
    "level":"16",
    "to":"Wartortle"
  },
  "Wartortle":{
    "level":"36",
    "to":"Blastoise"
  },
  "Caterpie":{
    "level":"7",
    "to":"Metapod"
  },
  "Metapod":{
    "level":"10",
    "to":"Butterfree"
  },
  "Weedle":{
    "level":"7",
    "to":"Kakuna"
  },
  "Kakuna":{
    "level":"10",
    "to":"Beedrill"
  },
  "Pidgey":{
    "level":"18",
    "to":"Pidgeotto"
  },
  "Pidgeotto":{
    "level":"36",
    "to":"Pidgeot"
  },
  "Rattata":{
    "level":"20",
    "to":"Raticate"
  },
  "Spearow":{
    "level":"20",
    "to":"Fearow"
  },
  "Ekans":{
    "level":"22",
    "to":"Arbok"
  },
  "Sandshrew":{
    "level":"22",
    "to":"Sandslash"
  },
  "Nidoran♀":{
    "level":"16",
    "to":"Nidorina"
  },
  "Nidoran♂":{
    "level":"16",
    "to":"Nidorino"
  },
  "Zubat":{
    "level":"22",
    "to":"Golbat"
  },
  "Oddish":{
    "level":"21",
    "to":"Gloom"
  },
  "Paras":{
    "level":"24",
    "to":"Parasect"
  },
  "Venonat":{
    "level":"31",
    "to":"Venomoth"
  },
  "Diglett":{
    "level":"26",
    "to":"Dugtrio"
  },
  "Meowth":{
    "level":"28",
    "to":"Persian"
  },
  "Psyduck":{
    "level":"33",
    "to":"Golduck"
  },
  "Mankey":{
    "level":"28",
    "to":"Primeape"
  },
  "Poliwag":{
    "level":"25",
    "to":"Poliwhirl"
  },
  "Abra":{
    "level":"16",
    "to":"Kadabra"
  },
  "Machop":{
    "level":"28",
    "to":"Machoke"
  },
  "Bellsprout":{
    "level":"21",
    "to":"Weepinbell"
  },
  "Tentacool":{
    "level":"30",
    "to":"Tentacruel"
  },
  "Geodude":{
    "level":"25",
    "to":"Graveler"
  },
  "Ponyta":{
    "level":"40",
    "to":"Rapidash"
  },
  "Slowpoke":{
    "level":"37",
    "to":"Slowbro"
  },
  "Magnemite":{
    "level":"30",
    "to":"Magneton"
  },
  "Doduo":{
    "level":"31",
    "to":"Dodrio"
  },
  "Seel":{
    "level":"34",
    "to":"Dewgong"
  },
  "Grimer":{
    "level":"38",
    "to":"Muk"
  },
  "Gastly":{
    "level":"25",
    "to":"Haunter"
  },
  "Drowzee":{
    "level":"26",
    "to":"Hypno"
  },
  "Krabby":{
    "level":"28",
    "to":"Kingler"
  },
  "Voltorb":{
    "level":"30",
    "to":"Electrode"
  },
  "Cubone":{
    "level":"28",
    "to":"Marowak"
  },
  "Tyrogue":{
    "level":"20",
    "to":"Hitmontop"
  },
  "Koffing":{
    "level":"35",
    "to":"Weezing"
  },
  "Rhyhorn":{
    "level":"42",
    "to":"Rhydon"
  },
  "Horsea":{
    "level":"32",
    "to":"Seadra"
  },
  "Goldeen":{
    "level":"33",
    "to":"Seaking"
  },
  "Smoochum":{
    "level":"30",
    "to":"Jynx"
  },
  "Elekid":{
    "level":"30",
    "to":"Electabuzz"
  },
  "Magby":{
    "level":"30",
    "to":"Magmar"
  },
  "Magikarp":{
    "level":"20",
    "to":"Gyarados"
  },
  "Omanyte":{
    "level":"40",
    "to":"Omastar"
  },
  "Kabuto":{
    "level":"40",
    "to":"Kabutops"
  },
  "Dratini":{
    "level":"30",
    "to":"Dragonair"
  },
  "Dragonair":{
    "level":"55",
    "to":"Dragonite"
  }
};

function checkEvolution( poke )
{
    var evolve = evolutions[ pokemonInfo[ poke - 1 ].pokemon[ 0 ].Pokemon ];
    if ( poke.level >= evolve.level )
    {
        return true;
    }
    else
    {
        return false;
    }
}
