const EVOLUTIONS = {
  "Bulbasaur":{
    "level":"35",
    "to":"Ivysaur"
  },
  "Ivysaur":{
    "level":"70",
    "to":"Venusaur"
  },
  "Charmander":{
    "level":"35",
    "to":"Charmeleon"
  },
  "Charmeleon":{
    "level":"70",
    "to":"Charizard"
  },
  "Squirtle":{
    "level":"35",
    "to":"Wartortle"
  },
  "Wartortle":{
    "level":"70",
    "to":"Blastoise"
  },
  "Caterpie":{
    "level":"10",
    "to":"Metapod"
  },
  "Metapod":{
    "level":"50",
    "to":"Butterfree"
  },
  "Weedle":{
    "level":"10",
    "to":"Kakuna"
  },
  "Kakuna":{
    "level":"50",
    "to":"Beedrill"
  },
  "Pidgey":{
    "level":"50",
    "to":"Pidgeotto"
  },
  "Pidgeotto":{
    "level":"80",
    "to":"Pidgeot"
  },
  "Rattata":{
    "level":"40",
    "to":"Raticate"
  },
  "Spearow":{
    "level":"40",
    "to":"Fearow"
  },
  "Ekans":{
    "level":"40",
    "to":"Arbok"
  },
  "Sandshrew":{
    "level":"70",
    "to":"Sandslash"
  },
  "Nidoran f":{
    "level":"40",
    "to":"Nidorina"
  },
  "Nidorina":{
    "level":"80",
    "to":"Nidoqueen"
  },
  "Nidoran m":{
    "level":"40",
    "to":"Nidorino"
  },
  "Nidorino":{
    "level":"80",
    "to":"Nidoking"
  },
  "Zubat":{
    "level":"50",
    "to":"Golbat"
  },
  "Oddish":{
    "level":"40",
    "to":"Gloom"
  },
  "Gloom":{
    "level":"70",
    "to":"Vileplume"
  },
  "Paras":{
    "level":"60",
    "to":"Parasect"
  },
  "Venonat":{
    "level":"50",
    "to":"Venomoth"
  },
  "Diglett":{
    "level":"60",
    "to":"Dugtrio"
  },
  "Meowth":{
    "level":"70",
    "to":"Persian"
  },
  "Psyduck":{
    "level":"80",
    "to":"Golduck"
  },
  "Mankey":{
    "level":"60",
    "to":"Primeape"
  },
  "Poliwag":{
    "level":"50",
    "to":"Poliwhirl"
  },
  "Poliwhirl":{
    "level":"80",
    "to":"Poliwrath"
  },
  "Abra":{
    "level":"50",
    "to":"Kadabra"
  },
  "Kadabra":{
    "level":"85",
    "to":"Alakazam"
  },
  "Machop":{
    "level":"50",
    "to":"Machoke"
  },
  "Machoke":{
    "level":"80",
    "to":"Machamp"
  },
  "Bellsprout":{
    "level":"50",
    "to":"Weepinbell"
  },
  "Weepinbell":{
    "level":"80",
    "to":"Victreebel"
  },
  "Tentacool":{
    "level":"60",
    "to":"Tentacruel"
  },
  "Geodude":{
    "level":"50",
    "to":"Graveler"
  },
  "Graveler":{
    "level":"75",
    "to":"Golem"
  },
  "Ponyta":{
    "level":"50",
    "to":"Rapidash"
  },
  "Slowpoke":{
    "level":"70",
    "to":"Slowbro"
  },
  "Magnemite":{
    "level":"70",
    "to":"Magneton"
  },
  "Doduo":{
    "level":"60",
    "to":"Dodrio"
  },
  "Seel":{
    "level":"60",
    "to":"Dewgong"
  },
  "Grimer":{
    "level":"60",
    "to":"Muk"
  },
  "Shellder":{
    "level":"60",
    "to":"Cloyster"
  },
  "Gastly":{
    "level":"80",
    "to":"Haunter"
  },
  "Haunter":{
    "level":"95",
    "to":"Gengar"
  },
  "Drowzee":{
    "level":"60",
    "to":"Hypno"
  },
  "Krabby":{
    "level":"60",
    "to":"Kingler"
  },
  "Voltorb":{
    "level":"70",
    "to":"Electrode"
  },
  "Cubone":{
    "level":"80",
    "to":"Marowak"
  },
  "Koffing":{
    "level":"60",
    "to":"Weezing"
  },
  "Rhyhorn":{
    "level":"85",
    "to":"Rhydon"
  },
  "Horsea":{
    "level":"60",
    "to":"Seadra"
  },
  "Goldeen":{
    "level":"60",
    "to":"Seaking"
  },
  "Magikarp":{
    "level":"95",
    "to":"Gyarados"
  },
  "Omanyte":{
    "level":"85",
    "to":"Omastar"
  },
  "Kabuto":{
    "level":"85",
    "to":"Kabutops"
  },
  "Dratini":{
    "level":"70",
    "to":"Dragonair"
  },
  "Dragonair":{
    "level":"90",
    "to":"Dragonite"
  }
};
